### ISSUE TITLE
Token validieren

### ISSUE THREAD

**Issue by MarEliSeg** [ob-vss-ss18/ppl-auth#15]
Bei jedem Request wird der Token auf Gültigkeit geprüft, da dieser nur eine gewisse Dauer gültig ist und nach Ablauf ein neuer Token generiert werden muss.

**Comment by MarEliSeg** [comment]
Absprache mit dem Core-Team, ob die Zuordnung des Token zum Kunden im auth-Service passiert, oder das der jeweilige Service, der anfragt übernimmt.

**Comment by skyfmmf** [comment]
Wir validieren nur E-Mail und Token des übergebenen Users
